// If no license, return an empty string
function renderLicenseBadge(license) {
    if (license === 'No License') {
      return ''
    }
    else if (license === 'Apache-2.0') {
      return '[![License](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)'
    }
    else if (license === 'Boost-1.0') {
      return '[![License](https://img.shields.io/badge/License-Boost_1.0-lightblue.svg)](https://www.boost.org/LICENSE_1_0.txt)'
    }
    else if (license === 'GNU GLP-v3.0') {
      return '[![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)'
    }
    else if (license === 'MIT') {
      return '[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)'
    }
  
  }
  
  // If there is no license, return an empty string
  function renderLicenseLink(license) {
    if (license === 'No License') {
      return ''
    }
    else if (license === 'Apache-2.0') {
      return 'https://opensource.org/licenses/Apache-2.0'
    }
    else if (license === 'Boost-1.0') {
      return 'https://www.boost.org/LICENSE_1_0.txt'
    }
    else if (license === 'GNU GLP-v3.0') {
      return 'https://www.gnu.org/licenses/gpl-3.0'
    }
    else if (license === 'MIT') {
      return 'https://opensource.org/licenses/MIT'
    }
  
  
  }
  
  // If there is no license, return an empty string
  function renderLicenseSection(license, year, holder) {
    if (license === 'No License') {
      return ''
    }
    else if (license === 'Apache-2.0') {
      return `
       Copyright (C) ${year} ${holder}
  
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at
   
        http://www.apache.org/licenses/LICENSE-2.0
   
      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.`
    }
    else if (license === 'Boost-1.0') {
      return `
      Copyright (C) ${year} ${holder}
  
      Permission is hereby granted, free of charge, to any person or organization
      obtaining a copy of the software and accompanying documentation covered by
      this license (the "Software") to use, reproduce, display, distribute,
      execute, and transmit the Software, and to prepare derivative works of the
      Software, and to permit third-parties to whom the Software is furnished to
      do so, all subject to the following:
      
      The copyright notices in the Software and this entire statement, including
      the above license grant, this restriction and the following disclaimer,
      must be included in all copies of the Software, in whole or in part, and
      all derivative works of the Software, unless such copies or derivative
      works are solely in the form of machine-executable object code generated by
      a source language processor.
      
      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
      FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
      SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
      FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
      ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
      DEALINGS IN THE SOFTWARE.`
    }
    else if (license === 'GNU GLP-v3.0') {
      return `
      Copyright (C) ${year} ${holder}
  
      This program is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.
  
      This program is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.
  
      You should have received a copy of the GNU General Public License
      along with this program.  If not, see <https://www.gnu.org/licenses/>.`
    }
    else if (license === 'MIT') {
      return `
      Copyright (C) ${year} ${holder}
  
     Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
  
     The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
  
     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`
    }
  
  }
  
  
  
  function generateMarkdown(data) {
    return `# ${data.title}
  
  ${renderLicenseBadge(data.license)}  
    
  ## Description
  
  ${data.description}
      
  ## Table of Contents
  
  - [Description](#description)
  - [Installation](#installation)
  - [Usage](#usage)
  - [Contributing](#contributing)
  - [Test](#test)
  - [License](#license)
  - [Questions](#questions)
  
  ## Installation
      
  ${data.installation}
  
  ## Usage
      
  ${data.usage}
      
  
  ${data.contributionGuidelines ? 
    `
    # Contributing
  
    ${data.contributionGuidelines}
    ` :
    `
    # Contributing
  
    Thanks! But I am not accepting foreign contributions at the moment.`
  }
  
  ## Test
  
  ${data.test}
  
  ## License
  
  ${renderLicenseSection(data.license, data.year, data.holder)}        
  ${renderLicenseLink(data.license)}
          
  ## Questions
  
  - You can reach me through https://github.com/${data.contact1}
  - Also, you can contact me through my e-mail: [${data.contact2}](mailto:${data.contact2}) if you have any question.
  `
  
  }
  
  module.exports = generateMarkdown;